name: Build Resume PDF

on:
  push:
    branches: [main]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cv.tex
          compiler: pdflatex

      - name: Rename PDF to desired filename
        run: mv cv.pdf abhishekprasad.pdf

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Resume-PDF
          path: abhishekprasad.pdf

      - name: Deploy PDF to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          destination_dir: .
          publish_branch: gh-pages
          keep_files: false
        if: github.ref == 'refs/heads/main'
