name: Build Resume PDF

on:
  push:
    branches: [main]
    paths: ["cv.tex"]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cv.tex
          compiler: pdflatex

      - name: Rename PDF to desired filename
        run: mv cv.pdf abhishekprasad.pdf

      - name: Commit and push updated PDF
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add abhishekprasad.pdf
          git diff --staged --quiet || git commit -m "Update resume PDF [skip ci]"
          git push
