# .github/workflows/build-and-deploy.yml
name: Build LaTeX CV and Deploy to GitHub Pages

on:
  push:
    branches: [main] # Change to 'master' if that's your default branch
  pull_request:
    branches: [main]
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra texlive-bibtex-extra latexmk

      - name: Compile LaTeX document
        run: |
          # Create output directory
          mkdir -p build

          # Compile the CV (try multiple engines in case one fails)
          if latexmk -pdf -output-directory=build cv.tex; then
            echo "Successfully compiled with pdflatex"
          elif latexmk -xelatex -output-directory=build cv.tex; then
            echo "Successfully compiled with xelatex"
          elif pdflatex -output-directory=build cv.tex; then
            echo "Successfully compiled with pdflatex (direct)"
          else
            echo "Compilation failed"
            exit 1
          fi

          # Copy PDF to a web-friendly name
          cp build/cv.pdf build/abhishekprasad.pdf

      - name: Create HTML index page
        run: |
          cat > build/index.html << EOF
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>My CV</title>
              <style>
                  body {
                      font-family: Arial, sans-serif;
                      max-width: 800px;
                      margin: 0 auto;
                      padding: 20px;
                      text-align: center;
                  }
                  .cv-container {
                      border: 1px solid #ddd;
                      border-radius: 8px;
                      padding: 20px;
                      margin: 20px 0;
                  }
                  .download-btn {
                      display: inline-block;
                      background-color: #007bff;
                      color: white;
                      padding: 10px 20px;
                      text-decoration: none;
                      border-radius: 5px;
                      margin: 10px;
                  }
                  .download-btn:hover {
                      background-color: #0056b3;
                  }
                  iframe {
                      width: 100%;
                      height: 800px;
                      border: none;
                  }
              </style>
          </head>
          <body>
              <h1>My Curriculum Vitae</h1>
              <div class="cv-container">
                  <a href="abhishekprasad.pdf" class="download-btn" download>Download PDF</a>
                  <a href="abhishekprasad.pdf" class="download-btn" target="_blank">Open in New Tab</a>
                  <iframe src="abhishekprasad.pdf" type="application/pdf">
                      <p>Your browser doesn't support PDF viewing. <a href="abhishekprasad.pdf">Download the PDF</a> instead.</p>
                  </iframe>
              </div>
              <p><small>Last updated: \$(date)</small></p>
          </body>
          </html>
          EOF

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
